DROP TABLE IF EXISTS customer;  
CREATE TABLE customer (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
name VARCHAR(50) NOT NULL,  
email VARCHAR(50) NOT NULL,  
phone VARCHAR(50) NOT NULL,  
ssn VARCHAR(50) NOT NULL 

);  